title: My Marsiling, My Future - Our Home, Our Heart, Our Hope!
url: https://staging-lite.d2kdgm7h8w0kte.amplifyapp.com
favicon: /images/Marsiling_Logo.png
colors:
  primary-color: "#e74822"
  secondary-color: "#db1e39"
  media-colors:
    - title: media-color-one
      color: "#ffc641"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#2d429a"
    - title: media-color-four
      color: "#e74822"
    - title: media-color-five
      color: "#afd135"
description: “M” is reminisce of the original logo, acknowledging the efforts
  and values of the Pioneers, and the next generation is committed to continue
  building Marsiling into the Home for all with a loving & caring Heart.
  Together, we will build a bright and vibrant future for all - Our Hope, Our
  Marsiling, One Marsiling
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1shh1ypto3fx4.amplifyapp.com
prod: https://master.d1shh1ypto3fx4.amplifyapp.com
facebook-pixel: ""
resources_name: news-and-updates
shareicon: /images/PA_Marsiling_Logo.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
